### ISSUE TITLE
Test .pro files.

### ISSUE THREAD

**Issue by HavenDV** [PO-21/QtReports#1]

**Comment by Syler1984** [comment]
Что не так с .pro файлами?

**Comment by Syler1984** [comment]
.pro для QtReportsViewer действительно не работает. Engine.h находит, но не видит не одной его функции "QtReports-master/QtReports/QtReportsViewer/main.cpp:-1: ошибка: undefined reference to `qtreports::Engine::Engine(QObject*)'"

**Comment by HavenDV** [comment]
Fixed. https://travis-ci.org/PO-21/QtReports/jobs/113036627
