### ISSUE TITLE
Implementation classes ObjectPlant and Translator.

### ISSUE THREAD

**Issue by HavenDV** [PO-21/QtReports#2]

**Comment by Syler1984** [comment]
Прикрепил к репозиторию файл с описанием тегов, буду обновлять его при появлении изменений.

При формировании структуры отчета использую функцию Object::set_param(QString, QVariant), чтобы задавать параметры объекта.

**Comment by Syler1984** [comment]
Т.к. один стиль может быть использован несколькими объектами, то удобнее связывать объект со стилем по идентификатору, а стили хранить отдельно от объектов. Теперь Translator формирует QVector из объектов Style и древовидную структуру отчета с корнем Report.
У Style есть функции для оперирования его id.
Идентификатор стиля можно задать объекту используя функцию set_style_id(int) или set_param(QString param, QVariant val) (cо строкой param = "style_id").

**Comment by Syler1984** [comment]
Parser должен возвращать еще и стили.
И я не понимаю, что такое ReportPtr?
Почему ты не используешь просто Report *?

**Comment by HavenDV** [comment]
ReportPtr - умный указатель, чтобы не было возни с памятью(Если наша библиотека будет возвращать просто указатель, его память надо будет самостоятельно удалять пользователю вызовом delete, к тому же не факт, что она больше не будет использоваться в библиотеке. А в случае с умным указателем - внутри идет подсчет ссылок на объект, как только он никому не нужен - он удаляется. Само использование идентично обычному разыменованию, к тому же есть проверка isNull() ). 
Подробнее можно прочитать в описании QSharedPointer.
Сам тип объявлен в report.hpp как:
typedef QSharedPointer< Report > ReportPtr;
Собственно, поэтому желательно вообще не использовать обычные указатели. Либо ссылки, либо умные указатели.

**Comment by Syler1984** [comment]
Для реализации парсера тебе понадобится знать, какие параметры задавать объектам (через функцию setParameter(QString, QVariant)), для этого скоординируйся с Кармановым - он реализует тэги. Но я попрошу его записать их названия и типы в соответствующий тэгам issue.

**Comment by Syler1984** [comment]
Пока первая группа не утвердила, как будут храниться скрипты и запросы. Но, добавь в парсер функции, которые возвращают запросы и скрипты (например, как QVector<QString>).

**Comment by HavenDV** [comment]
https://github.com/PO-21/QtReports/commit/9c80614ef885b853743d89b167922dbde1dabd52

**Comment by HavenDV** [comment]
Parser реализован и поддерживает простое добавление новых тегов.
