### ISSUE TITLE
Implementation of ProcessedDB

### ISSUE THREAD

**Issue by HavenDV** [PO-21/QtReports#35]

**Comment by HavenDV** [comment]
https://github.com/PO-21/QtReports/commit/3f3836c4b426e668711f3636c0dc3c938bc00fef
Проверь, пришлось вручную соединять patch1 и patch2. 
Ветка develop открыта для commit-ов, не обязательно создавать новые ветки.

**Comment by KarmannO** [comment]
Промахнулся с коммитом, не в той директории закоммитил, теперь норм. Как файлы из корня удалить?

**Comment by HavenDV** [comment]
Исправил. Как мне получить количество строк для раскрытия detail? При чем, как я понимаю, количество строк у всех столбцов должно совпадать.

**Comment by KarmannO** [comment]
Не должно, m_columnsSet заполняется непосредственно в процессе выполнения всех запросов. Количество строк в соответствующем столбце это getColumn(colName).size();

**Comment by KarmannO** [comment]
Могу вынести в отдельный метод получения (надо было сначала так и сделать)...

**Comment by HavenDV** [comment]
Ага, выноси. Тогда как мне заполнять detail, если часть столбцов имеет один размер, а часть другой? Пустые строки? И что в этом случае делает jasper

**Comment by HavenDV** [comment]
И, как я понимаю, detail должно раскрываться в max( column[ 0 ].size() ... column[ n ].size() ) строк. Тоже желательно вынести

**Comment by Syler1984** [comment]
По поводу разного размера столбцов. Если ты заполняешь detail и столкнулся с тем, что в Band(е) некоторые textField(ы) закончились то ты их выводишь пустыми.
Если в Band(е) нет ни одного заполненого поля, то не выводи Band вообще.

**Comment by KarmannO** [comment]
Сейчас поправлю код с добавлением getRowCount для каждой колонки и getMaxRowCount
