### ISSUE TITLE
Implementation of Painter class

### ISSUE THREAD

**Issue by Syler1984** [PO-21/QtReports#5]
Класс Painter отвечает за экспорт готового отчета в графические форматы. 
Painter предоставляет средства для рисования, которые используются объектами отчета (строки, таблицы, изображения и пр.).
Порядок рисования следующий:
1. Вызывается функция, сообщающая о начале рисования в конкретный файл, например:
beginPDF_Drawing.
2. Объект вызывает функцию beginObjectDrawing.
3. Объект сообщает область, в которой будет происходить рисование setWorkspace.
4. Объект задает стиль рисования и рисует.
5. Объект сообщает о завершении рисования на данной странице endObjectDrawing.
6. Создается новая страница newPage, если был послан запрос на ее создание newPageRequest и п. 2-6 повторяются.

**Comment by HavenDV** [comment]
https://github.com/PO-21/QtReports/commit/7e75460db9c8841be7cad6c4a2e0bc91bf56a12c

**Comment by HavenDV** [comment]
Отказались от использования
