### ISSUE TITLE
Implementation of tags classes

### ISSUE THREAD

**Issue by Syler1984** [PO-21/QtReports#6]

**Comment by Syler1984** [comment]
Большинство тэгов унаследованы от класса Object. Для нормальной работы тэга требуется переопределить следующие функции:
bool    drawSelf( Painter & painter, const ProcessedDB & db ) - рисует сам объект.
bool    prepareChilds( Painter & painter, const ProcessedDB & db ) - вносит изменения в дочерние элементы объекта, если это требуется.
bool    setParameter( const QString & name, const QVariant & value ) - задает параметру объекта с именем name значение value.

Функции drawSelf и prepareChilds могут генерировать исключения DrawingExeption.

Функция setParameter в случае ошибки возвращает false и запоминает возникшую ошибку, которую можно получить при помощи getLastError.

**Comment by HavenDV** [comment]
https://github.com/PO-21/QtReports/commit/9c80614ef885b853743d89b167922dbde1dabd52
https://github.com/PO-21/QtReports/commit/a921e386c484c6ab19e9dee12929296ac5847269

**Comment by HavenDV** [comment]
Ожидается реализация тэга Field.
В планах реализация поддержки Style и отдельных атрибутов для управления шрифтом.

**Comment by HavenDV** [comment]
Тэг FIeld реализован.

**Comment by Syler1984** [comment]
Style по умолчанию должен быть разным для разных тегов. Для StaticText, например, один стиль по умолчанию, а для Line - другой.

**Comment by Syler1984** [comment]
Есть ли возможность получить ориентацию отчета?

**Comment by HavenDV** [comment]
Добавил. Report::getOrientation.
