### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by Werzet** [PO-21/QtReports#7]

**Comment by 3LIZIUM** [comment]
engine.hpp пусто ни одного комментария(

**Comment by 3LIZIUM** [comment]
Я в папке QtReports/qtreportslib/ обрабатываю .hpp . Можешь просмотреть что я уже сделал? [Look](https://github.com/PO-21/QtReports/wiki/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8)
И если будет возможность можешь подключить своих ребят и прокоментировать, посмотреть, подправить??? буду очень признателен. 
Любая помощь, исправления, критика мне будет полезна, так что чуть что пиши, пишите!!!

**Comment by HavenDV** [comment]
Еще аргументы нужно описывать. Я [здесь](https://github.com/PO-21/QtReports/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B) приводил пример.

**Comment by 3LIZIUM** [comment]
так в этом и дело, я интуитивно могу сказать что и зачем, НО это может быть не так, потому мне желательно связь с "создателем"

**Comment by HavenDV** [comment]
https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html изучайте и вам не прийдеться создавать страницы для каждого класса

Автоматом будет создаваться такое - http://po-21.github.io/html/annotated.html

**Comment by HavenDV** [comment]
Вся документация классов перенесена на отдельный сайт. Генерация происходит с помощью программы doxygen. Документация тэгов завершена на 60%.

**Comment by 3LIZIUM** [comment]
Обновлен тег ReportElement

**Comment by HavenDV** [comment]
Уверены, что стиль - обязательный атрибут?

**Comment by HavenDV** [comment]
По документации - https://travis-ci.org/PO-21/QtReports/builds
clang показывает ошибки, связанные с документацией( описали не те входные переменные и т.п )

**Comment by HavenDV** [comment]
https://travis-ci.org/PO-21/QtReports/jobs/121611684
Вот список текущих ошибок по документации... Копипаст, это хорошо, но не настолько(
